name: GetAJob
version: '1.0-SNAPSHOT'
main: org.radi8.getAJob.GetAJob
api-version: '1.20'
authors: [ Andrew (radi8) ]
description: Per-day time limiting on Minecraft servers

commands:
  get-time:
    description: get time of all players
    usage: /<command>

  leaderboard:
    description: get leaderboard of the time players have spent that day
    usage: /<command>